package amiconnected;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonhard
 * @version 1.0
 */
public class Gui extends javax.swing.JFrame {

    private Thread testing;
    private int tries;
    private final String google;

    /**
     * Creates new form Frame
     */
    public Gui() {
        //setVisible(true);
        google = "http://www.google.com";
        tries = 0;
        this.setLocationRelativeTo(null);
        initComponents();
        setIcon();
        setVisible(true);
        testing = new Connecter(this, google);
        testing.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_connected = new javax.swing.JLabel();
        t_adress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b_start = new javax.swing.JButton();
        cb_loop = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        l_tries = new javax.swing.JLabel();
        b_kill = new javax.swing.JButton();
        l_took = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b_help = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cb_sound = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Am I connected?");
        setResizable(false);

        l_connected.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        l_connected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        t_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_adressActionPerformed(evt);
            }
        });
        t_adress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_adressKeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Host: (if empty, http://www.google.com is used)");

        b_start.setText("Check Connection");
        b_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_startActionPerformed(evt);
            }
        });

        cb_loop.setText("Run as Loop");
        cb_loop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loopActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Am I connected?");

        l_tries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_tries.setText("0 Versuche");
        l_tries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_triesMouseClicked(evt);
            }
        });

        b_kill.setText("X");
        b_kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_killActionPerformed(evt);
            }
        });

        l_took.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("(c) Leonhard Kuenzler - 2014");

        b_help.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b_help.setText("Show help");
        b_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_helpActionPerformed(evt);
            }
        });

        cb_sound.setSelected(true);
        cb_sound.setText("Play Sound");
        cb_sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_soundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(l_tries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(l_connected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_adress)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_sound)
                            .addComponent(cb_loop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_kill))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(b_help, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(l_took, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_start, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cb_loop, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_sound, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_kill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_connected, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(l_took, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_tries)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(b_help))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_adressActionPerformed
    }//GEN-LAST:event_t_adressActionPerformed

    private void b_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_startActionPerformed
        kill();
        l_took.setText("");
        b_kill.setEnabled(true);
        l_connected.setText("...");
        String adress = t_adress.getText();
        if (adress.equals("")) {
            adress = google;
        } else if (adress.equals("anselm") || adress.equals("Anselm") || adress.equals("Anselm Binninger")) {
            message("Ich hab genau gewusst, dass\n"
                    + "du deinen Namen eingibst :D\n\nSpast :D");
        } else if (adress.equals("fredi") || adress.equals("Fredi") || adress.equals("Frederik Mattwich")) {
            message("Deine Mutter ist so fett, wenn sie\n"
                    + "auf den Times Square geht, wird sie wegen\n"
                    + "illegaler Massenveranstaltung verhaftet.");
        }
        if (cb_loop.isSelected()) {
            testing = new Loop(this, adress);
        } else {
            testing = new Connecter(this, adress);
        }
        testing.start();
    }//GEN-LAST:event_b_startActionPerformed

    private void cb_loopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loopActionPerformed
    }//GEN-LAST:event_cb_loopActionPerformed

    private void b_killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_killActionPerformed
        kill();
        b_kill.setEnabled(false);
    }//GEN-LAST:event_b_killActionPerformed

    private void t_adressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_adressKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            b_start.doClick();
        }
    }//GEN-LAST:event_t_adressKeyPressed

    private void l_triesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_triesMouseClicked
        tries = 0;
        setTries();
        l_took.setText("");
    }//GEN-LAST:event_l_triesMouseClicked

    private void b_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_helpActionPerformed
        message("This programm shows you, if you are connected to the internet.\n"
                + "If you use it in loop mode, it will try until it has a connection.\n"
                + "The programm plays a sound, if the connection attempt was successful.\n "
                + "The time shown is the time from last attempt to answer from host. \n"
                + "Standard host is http://www.google.com. If you want to reset the\n"
                + "counter, just click it. To view your latency, use without loop mode.\n"
                + "\n\nLeonhard Künzler - (c) 2014\nleo@bwk-technik.de\n\n"
                + "BWK Technik - www.bwk-technik.de");
    }//GEN-LAST:event_b_helpActionPerformed

    private void cb_soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_soundActionPerformed
    }//GEN-LAST:event_cb_soundActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_help;
    private javax.swing.JButton b_kill;
    private javax.swing.JButton b_start;
    private javax.swing.JCheckBox cb_loop;
    private javax.swing.JCheckBox cb_sound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_connected;
    private javax.swing.JLabel l_took;
    private javax.swing.JLabel l_tries;
    private javax.swing.JTextField t_adress;
    // End of variables declaration//GEN-END:variables

    public void setConnected(boolean connected) {
        tries++;
        setTries();
        if (connected) {
            l_connected.setText("Yes");
            kill();
            b_kill.setEnabled(false);
        } else {
            l_connected.setText("No :(");
        }
    }

    private void setIcon() {
        java.net.URL iconUrl = this.getClass().getResource("connection.png");
        java.awt.Image img = getToolkit().getImage(iconUrl);
        setIconImage(img);
    }

    public void setTries() {
        String attempts = "attempts";
        if (tries == 1) {
            attempts = "attempt";
        }
        l_tries.setText(tries + " " + attempts);
    }

    public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void kill() {
        if (testing instanceof Loop) {
            ((Loop) testing).kill();
        }
    }

    public boolean getSound() {
        return (cb_sound.isSelected());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            //
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gui();
            }
        });
    }

    void setTook(long time) {
        l_took.setText("Successful try took " + time + "ms");
    }
}
